# Generated by Django 5.1.6 on 2025-06-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='points_required',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
