# Generated by Django 4.2.7 on 2025-06-22 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_reward_points_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='signup_source',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile App')], default='web', max_length=20),
        ),
    ]
