# Generated by Django 4.2.7 on 2025-07-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_bottles_recycled_profile_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='points_required',
        ),
        migrations.AddField(
            model_name='reward',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='cost',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(default=0, upload_to='rewards/'),
            preserve_default=False,
        ),
    ]
