# Generated by Django 4.2.7 on 2025-07-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_reward_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='cost',
            field=models.IntegerField(default=10),
        ),
    ]
