# Generated by Django 4.2.7 on 2025-07-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_reward_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='claimed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reward',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reward_images/'),
        ),
    ]
