# Generated by Django 4.2.7 on 2025-07-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_reward_claimed_count_reward_total_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
