# Generated by Django 4.2.7 on 2025-07-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_reward_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='claimed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
