# Generated by Django 5.1.6 on 2025-07-11 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_address_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
