# Generated by Django 5.1.6 on 2025-07-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='signup_source',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile App')], default='web', max_length=10),
        ),
    ]
