# Generated by Django 5.2.7 on 2025-10-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_claimrequest_claim_expiry_date_claimrequest_claim_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrequest',
            name='claim_expiry_date',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='claim_id',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='claimed_at',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='scheduled_claim_date',
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
