# Generated by Django 5.2.7 on 2025-10-11 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_claimrequest_claim_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimrequest',
            options={},
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='redemption_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='reason',
            field=models.TextField(blank=True, default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.reward'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
