# Generated by Django 5.2.7 on 2025-10-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_claimrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
