# Generated by Django 5.2.7 on 2025-10-11 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_claimrequest_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='redemption_id',
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='accounts.reward'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
