# Generated by Django 5.2.4 on 2025-10-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_claimrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='claim_code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='claim_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
