# Generated by Django 5.2.4 on 2025-10-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_claimrequest_claim_code_claimrequest_claim_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrequest',
            name='claim_code',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='claim_date',
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (optional)', null=True),
        ),
    ]
