# Generated by Django 5.2.4 on 2025-10-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_claimrequest_claim_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
