# Generated by Django 5.2.4 on 2025-10-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_reward_remaining_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='remaining_quantity',
        ),
    ]
