# Generated by Django 5.2.4 on 2025-10-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_reward_remaining_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='unique_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
