# Generated by Django 5.2.4 on 2025-10-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_claimrequest_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='claim_by_date',
            field=models.DateField(blank=True, help_text='Date by which the reward must be claimed', null=True),
        ),
    ]
