# Generated by Django 4.2.7 on 2025-10-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_passwordresetotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='code',
            new_name='otp',
        ),
    ]
